/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 02 11:16:43 GMT 2021
 */

package org.jhotdraw.samples.net;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jhotdraw.api.app.Application;
import org.jhotdraw.api.app.View;
import org.jhotdraw.app.CrossPlatformApplication;
import org.jhotdraw.app.OSXApplication;
import org.jhotdraw.app.SDIApplication;
import org.jhotdraw.samples.net.NetApplicationModel;
import org.jhotdraw.samples.teddy.TeddyView;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NetApplicationModel_ESTest extends NetApplicationModel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NetApplicationModel netApplicationModel0 = new NetApplicationModel();
      CrossPlatformApplication crossPlatformApplication0 = new CrossPlatformApplication();
      TeddyView teddyView0 = new TeddyView();
      // Undeclared exception!
      try { 
        netApplicationModel0.createToolBars(crossPlatformApplication0, teddyView0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jhotdraw.samples.teddy.TeddyView cannot be cast to org.jhotdraw.samples.net.NetView
         //
         verifyException("org.jhotdraw.samples.net.NetApplicationModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NetApplicationModel netApplicationModel0 = new NetApplicationModel();
      // Undeclared exception!
      try { 
        netApplicationModel0.createActionMap((Application) null, (View) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jhotdraw.action.AbstractApplicationAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NetApplicationModel netApplicationModel0 = new NetApplicationModel();
      OSXApplication oSXApplication0 = new OSXApplication();
      TeddyView teddyView0 = new TeddyView();
      // Undeclared exception!
      try { 
        netApplicationModel0.createActionMap(oSXApplication0, teddyView0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/jhotdraw/gui/event/SheetListener
         //
         verifyException("org.jhotdraw.app.DefaultApplicationModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NetApplicationModel netApplicationModel0 = new NetApplicationModel();
      SDIApplication sDIApplication0 = new SDIApplication();
      TeddyView teddyView0 = new TeddyView();
      teddyView0.enableInputMethods(false);
      // Undeclared exception!
      try { 
        netApplicationModel0.createOpenChooser(sDIApplication0, teddyView0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/jhotdraw/gui/JFileURIChooser
         //
         verifyException("org.jhotdraw.samples.net.NetApplicationModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NetApplicationModel netApplicationModel0 = new NetApplicationModel();
      netApplicationModel0.createMenuBuilder();
      Application application0 = null;
      View view0 = null;
      // Undeclared exception!
      try { 
        netApplicationModel0.createSaveChooser((Application) null, (View) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/jhotdraw/gui/JFileURIChooser
         //
         verifyException("org.jhotdraw.samples.net.NetApplicationModel", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NetApplicationModel netApplicationModel0 = new NetApplicationModel();
      CrossPlatformApplication crossPlatformApplication0 = new CrossPlatformApplication();
      crossPlatformApplication0.getActiveView();
      netApplicationModel0.initView(crossPlatformApplication0, (View) null);
      netApplicationModel0.getSharedEditor();
      // Undeclared exception!
      try { 
        netApplicationModel0.createToolBars(crossPlatformApplication0, (View) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/jhotdraw/gui/action/ButtonFactory
         //
         verifyException("org.jhotdraw.samples.net.NetApplicationModel", e);
      }
  }
}
