/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat May 29 11:06:50 GMT 2021
 */

package org.jhotdraw.draw.layouter;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class HorizontalLayouter_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.jhotdraw.draw.layouter.HorizontalLayouter"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.OFF; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(HorizontalLayouter_ESTest_scaffolding.class.getClassLoader() ,
      "org.jhotdraw.draw.figure.Figure",
      "org.jhotdraw.draw.liner.Liner",
      "org.jhotdraw.geom.Insets2D",
      "org.jhotdraw.draw.tool.Tool",
      "org.jhotdraw.geom.Insets2D$Double",
      "org.jhotdraw.geom.BezierPath$Node",
      "org.jhotdraw.draw.connector.Connector",
      "org.jhotdraw.geom.Dimension2DDouble",
      "org.jhotdraw.draw.event.CompositeFigureEvent",
      "org.jhotdraw.draw.AttributeKey",
      "org.jhotdraw.draw.AttributeKeys$WindingRule",
      "org.jhotdraw.draw.AttributeKeys$StrokeType",
      "org.jhotdraw.util.LocaleUtil",
      "org.jhotdraw.draw.DrawingView",
      "org.jhotdraw.draw.event.ToolEvent",
      "org.jhotdraw.draw.layouter.Layouter",
      "org.jhotdraw.draw.AttributeKeys$Orientation",
      "org.jhotdraw.draw.DrawingEditor",
      "org.jhotdraw.draw.TranslationDirection",
      "org.jhotdraw.draw.AttributeKeys$Underfill",
      "org.jhotdraw.util.ResourceBundleUtil",
      "org.jhotdraw.draw.layouter.HorizontalLayouter$1",
      "org.jhotdraw.draw.event.ToolListener",
      "org.jhotdraw.draw.RotationDirection",
      "org.jhotdraw.draw.figure.CompositeFigure",
      "org.jhotdraw.draw.figure.ConnectionFigure",
      "org.jhotdraw.draw.event.FigureSelectionListener",
      "org.jhotdraw.draw.AttributeKeys$StrokePlacement",
      "org.jhotdraw.draw.AttributeKeys$Alignment",
      "org.jhotdraw.draw.layouter.HorizontalLayouter",
      "org.jhotdraw.geom.BezierPath",
      "org.jhotdraw.draw.layouter.AbstractLayouter",
      "org.jhotdraw.draw.decoration.LineDecoration",
      "org.jhotdraw.draw.event.CompositeFigureListener",
      "org.jhotdraw.draw.AttributeKeys",
      "org.jhotdraw.draw.Constrainer",
      "org.jhotdraw.draw.event.FigureSelectionEvent"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(HorizontalLayouter_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.jhotdraw.draw.layouter.AbstractLayouter",
      "org.jhotdraw.draw.layouter.HorizontalLayouter",
      "org.jhotdraw.util.ResourceBundleUtil",
      "org.jhotdraw.util.LocaleUtil",
      "org.jhotdraw.draw.AttributeKey",
      "org.jhotdraw.draw.AttributeKeys$WindingRule",
      "org.jhotdraw.draw.AttributeKeys$Underfill",
      "org.jhotdraw.draw.AttributeKeys$StrokeType",
      "org.jhotdraw.draw.AttributeKeys$StrokePlacement",
      "org.jhotdraw.geom.Dimension2DDouble",
      "org.jhotdraw.draw.AttributeKeys$Alignment",
      "org.jhotdraw.geom.Insets2D",
      "org.jhotdraw.geom.Insets2D$Double",
      "org.jhotdraw.draw.AttributeKeys$Orientation",
      "org.jhotdraw.draw.AttributeKeys",
      "org.jhotdraw.draw.layouter.HorizontalLayouter$1",
      "org.jhotdraw.draw.figure.CompositeFigure"
    );
  }
}
